- name: Copy configuration for proxy and storage
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ qasmat_user }}"
    group: "{{ qasmat_user }}"
    mode: "0700"
  loop:
  - src: proxy-config.json.j2
    dest: /Qasmat/config/proxy-config.json
  - src: storage-config-storage1.json.j2
    dest: /Qasmat/config/storage-config-storage1.json
  - src: storage-config-storage2.json.j2
    dest: /Qasmat/config/storage-config-storage2.json
  - src: storage-config-storage3.json.j2
    dest: /Qasmat/config/storage-config-storage3.json
