name: Redeploy Qasmat Swarm Stack (with new config)

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      attestations: write
      id-token: write
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python and Install Ansible
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: |
        python -m pip install --upgrade pip
        pip install ansible-core

    - name: Install Ansible Dependencies
      run: |
        if [ -f requirements.yaml ]; then
          ansible-galaxy install -r requirements.yaml
        fi
    
    - name: Configure SSH and Inventory
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
        echo "${{ secrets.ANSIBLE_INVENTORY }}" > inventory.yaml

    - name: Run Ansible Playbook with GitHub Secrets
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'
      run: |
        ansible-playbook -i inventory.yaml playbooks/remove.yaml && \
        ansible-playbook -i inventory.yaml playbooks/deploy.yaml
